# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-25 14:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='flag_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flag', models.CharField(max_length=40)),
                ('osystem', models.CharField(max_length=10)),
                ('score', models.IntegerField()),
                ('title_name', models.CharField(max_length=20)),
                ('title_description', models.CharField(max_length=40)),
                ('degree_of_difficulty', models.CharField(max_length=2)),
                ('team_name', models.CharField(max_length=20)),
                ('ip_address', models.GenericIPAddressField()),
                ('submit_time', models.DateTimeField(auto_now=True)),
                ('submit_flag', models.CharField(max_length=40)),
                ('result', models.IntegerField()),
                ('times', models.IntegerField()),
            ],
            options={
                'ordering': ('ip_address',),
            },
        ),
        migrations.CreateModel(
            name='yunwei_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timu_ID', models.IntegerField()),
                ('timu_os', models.CharField(max_length=10)),
                ('timu_name', models.CharField(max_length=20)),
                ('timu_score', models.IntegerField()),
                ('timu_result', models.IntegerField()),
                ('timu_date', models.DateTimeField(auto_now=True)),
                ('timu_defensive', models.IntegerField()),
                ('timu_ip', models.CharField(max_length=20)),
            ],
        ),
    ]
